version: "3"

services:

  php:
    build:
      context: "."
      args:
        PHP_VERSION: "${PHP_VERSION:-8.0}"
    volumes:
    - ".:/app"
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: "/app"
